// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.27.1
// 	protoc        v3.6.1
// source: pozo.proto

package pozo

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Monto struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	CantidadTotal int32 `protobuf:"varint,1,opt,name=CantidadTotal,proto3" json:"CantidadTotal,omitempty"`
}

func (x *Monto) Reset() {
	*x = Monto{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pozo_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Monto) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Monto) ProtoMessage() {}

func (x *Monto) ProtoReflect() protoreflect.Message {
	mi := &file_pozo_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Monto.ProtoReflect.Descriptor instead.
func (*Monto) Descriptor() ([]byte, []int) {
	return file_pozo_proto_rawDescGZIP(), []int{0}
}

func (x *Monto) GetCantidadTotal() int32 {
	if x != nil {
		return x.CantidadTotal
	}
	return 0
}

var File_pozo_proto protoreflect.FileDescriptor

var file_pozo_proto_rawDesc = []byte{
	0x0a, 0x0a, 0x70, 0x6f, 0x7a, 0x6f, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x04, 0x70, 0x6f,
	0x7a, 0x6f, 0x22, 0x2d, 0x0a, 0x05, 0x4d, 0x6f, 0x6e, 0x74, 0x6f, 0x12, 0x24, 0x0a, 0x0d, 0x43,
	0x61, 0x6e, 0x74, 0x69, 0x64, 0x61, 0x64, 0x54, 0x6f, 0x74, 0x61, 0x6c, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x05, 0x52, 0x0d, 0x43, 0x61, 0x6e, 0x74, 0x69, 0x64, 0x61, 0x64, 0x54, 0x6f, 0x74, 0x61,
	0x6c, 0x32, 0x35, 0x0a, 0x0b, 0x50, 0x6f, 0x7a, 0x6f, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65,
	0x12, 0x26, 0x0a, 0x08, 0x47, 0x65, 0x74, 0x4d, 0x6f, 0x6e, 0x74, 0x6f, 0x12, 0x0b, 0x2e, 0x70,
	0x6f, 0x7a, 0x6f, 0x2e, 0x4d, 0x6f, 0x6e, 0x74, 0x6f, 0x1a, 0x0b, 0x2e, 0x70, 0x6f, 0x7a, 0x6f,
	0x2e, 0x4d, 0x6f, 0x6e, 0x74, 0x6f, 0x22, 0x00, 0x42, 0x24, 0x5a, 0x22, 0x67, 0x69, 0x74, 0x68,
	0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x42, 0x65, 0x6e, 0x6a, 0x61, 0x2d, 0x39, 0x39, 0x2f,
	0x74, 0x61, 0x72, 0x65, 0x61, 0x31, 0x5f, 0x53, 0x44, 0x2f, 0x70, 0x6f, 0x7a, 0x6f, 0x62, 0x06,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_pozo_proto_rawDescOnce sync.Once
	file_pozo_proto_rawDescData = file_pozo_proto_rawDesc
)

func file_pozo_proto_rawDescGZIP() []byte {
	file_pozo_proto_rawDescOnce.Do(func() {
		file_pozo_proto_rawDescData = protoimpl.X.CompressGZIP(file_pozo_proto_rawDescData)
	})
	return file_pozo_proto_rawDescData
}

var file_pozo_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_pozo_proto_goTypes = []interface{}{
	(*Monto)(nil), // 0: pozo.Monto
}
var file_pozo_proto_depIdxs = []int32{
	0, // 0: pozo.PozoService.GetMonto:input_type -> pozo.Monto
	0, // 1: pozo.PozoService.GetMonto:output_type -> pozo.Monto
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_pozo_proto_init() }
func file_pozo_proto_init() {
	if File_pozo_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_pozo_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Monto); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_pozo_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_pozo_proto_goTypes,
		DependencyIndexes: file_pozo_proto_depIdxs,
		MessageInfos:      file_pozo_proto_msgTypes,
	}.Build()
	File_pozo_proto = out.File
	file_pozo_proto_rawDesc = nil
	file_pozo_proto_goTypes = nil
	file_pozo_proto_depIdxs = nil
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// PozoServiceClient is the client API for PozoService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type PozoServiceClient interface {
	GetMonto(ctx context.Context, in *Monto, opts ...grpc.CallOption) (*Monto, error)
}

type pozoServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewPozoServiceClient(cc grpc.ClientConnInterface) PozoServiceClient {
	return &pozoServiceClient{cc}
}

func (c *pozoServiceClient) GetMonto(ctx context.Context, in *Monto, opts ...grpc.CallOption) (*Monto, error) {
	out := new(Monto)
	err := c.cc.Invoke(ctx, "/pozo.PozoService/GetMonto", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// PozoServiceServer is the server API for PozoService service.
type PozoServiceServer interface {
	GetMonto(context.Context, *Monto) (*Monto, error)
}

// UnimplementedPozoServiceServer can be embedded to have forward compatible implementations.
type UnimplementedPozoServiceServer struct {
}

func (*UnimplementedPozoServiceServer) GetMonto(context.Context, *Monto) (*Monto, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetMonto not implemented")
}

func RegisterPozoServiceServer(s *grpc.Server, srv PozoServiceServer) {
	s.RegisterService(&_PozoService_serviceDesc, srv)
}

func _PozoService_GetMonto_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Monto)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PozoServiceServer).GetMonto(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pozo.PozoService/GetMonto",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PozoServiceServer).GetMonto(ctx, req.(*Monto))
	}
	return interceptor(ctx, in, info, handler)
}

var _PozoService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "pozo.PozoService",
	HandlerType: (*PozoServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetMonto",
			Handler:    _PozoService_GetMonto_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "pozo.proto",
}
