// Code generated by protoc-gen-go. DO NOT EDIT.
// source: pozo.proto

package pozo

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Monto struct {
	CantidadTotal        int32    `protobuf:"varint,1,opt,name=CantidadTotal,proto3" json:"CantidadTotal,omitempty"`
	Monto2               int32    `protobuf:"varint,2,opt,name=monto2,proto3" json:"monto2,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Monto) Reset()         { *m = Monto{} }
func (m *Monto) String() string { return proto.CompactTextString(m) }
func (*Monto) ProtoMessage()    {}
func (*Monto) Descriptor() ([]byte, []int) {
	return fileDescriptor_8c8d761ddec175bc, []int{0}
}

func (m *Monto) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Monto.Unmarshal(m, b)
}
func (m *Monto) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Monto.Marshal(b, m, deterministic)
}
func (m *Monto) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Monto.Merge(m, src)
}
func (m *Monto) XXX_Size() int {
	return xxx_messageInfo_Monto.Size(m)
}
func (m *Monto) XXX_DiscardUnknown() {
	xxx_messageInfo_Monto.DiscardUnknown(m)
}

var xxx_messageInfo_Monto proto.InternalMessageInfo

func (m *Monto) GetCantidadTotal() int32 {
	if m != nil {
		return m.CantidadTotal
	}
	return 0
}

func (m *Monto) GetMonto2() int32 {
	if m != nil {
		return m.Monto2
	}
	return 0
}

func init() {
	proto.RegisterType((*Monto)(nil), "pozo.Monto")
}

func init() { proto.RegisterFile("pozo.proto", fileDescriptor_8c8d761ddec175bc) }

var fileDescriptor_8c8d761ddec175bc = []byte{
	// 170 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0x2a, 0xc8, 0xaf, 0xca,
	0xd7, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62, 0x01, 0xb1, 0x95, 0x5c, 0xb9, 0x58, 0x7d, 0xf3,
	0xf3, 0x4a, 0xf2, 0x85, 0x54, 0xb8, 0x78, 0x9d, 0x13, 0xf3, 0x4a, 0x32, 0x53, 0x12, 0x53, 0x42,
	0xf2, 0x4b, 0x12, 0x73, 0x24, 0x18, 0x15, 0x18, 0x35, 0x58, 0x83, 0x50, 0x05, 0x85, 0xc4, 0xb8,
	0xd8, 0x72, 0x41, 0xca, 0x8d, 0x24, 0x98, 0xc0, 0xd2, 0x50, 0x9e, 0x51, 0x2c, 0x17, 0x77, 0x40,
	0x7e, 0x55, 0x7e, 0x70, 0x6a, 0x51, 0x59, 0x66, 0x72, 0xaa, 0x90, 0x1a, 0x17, 0x87, 0x7b, 0x6a,
	0x09, 0xc4, 0x60, 0x6e, 0x3d, 0xb0, 0xa5, 0x60, 0x8e, 0x14, 0x32, 0x47, 0x89, 0x01, 0xa4, 0x2e,
	0x98, 0x08, 0x75, 0x4e, 0x2a, 0x51, 0x4a, 0xe9, 0x99, 0x25, 0x19, 0xa5, 0x49, 0x7a, 0xc9, 0xf9,
	0xb9, 0xfa, 0x4e, 0xa9, 0x79, 0x59, 0x89, 0xba, 0x96, 0x96, 0xfa, 0x25, 0x89, 0x45, 0xa9, 0x89,
	0x86, 0xf1, 0xc1, 0x2e, 0xfa, 0x20, 0xd5, 0x49, 0x6c, 0x60, 0x8f, 0x19, 0x03, 0x02, 0x00, 0x00,
	0xff, 0xff, 0x90, 0x55, 0x00, 0x40, 0xe6, 0x00, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// PozoServiceClient is the client API for PozoService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type PozoServiceClient interface {
	GetMonto(ctx context.Context, in *Monto, opts ...grpc.CallOption) (*Monto, error)
	SetMonto(ctx context.Context, in *Monto, opts ...grpc.CallOption) (*Monto, error)
}

type pozoServiceClient struct {
	cc *grpc.ClientConn
}

func NewPozoServiceClient(cc *grpc.ClientConn) PozoServiceClient {
	return &pozoServiceClient{cc}
}

func (c *pozoServiceClient) GetMonto(ctx context.Context, in *Monto, opts ...grpc.CallOption) (*Monto, error) {
	out := new(Monto)
	err := c.cc.Invoke(ctx, "/pozo.PozoService/GetMonto", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *pozoServiceClient) SetMonto(ctx context.Context, in *Monto, opts ...grpc.CallOption) (*Monto, error) {
	out := new(Monto)
	err := c.cc.Invoke(ctx, "/pozo.PozoService/SetMonto", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// PozoServiceServer is the server API for PozoService service.
type PozoServiceServer interface {
	GetMonto(context.Context, *Monto) (*Monto, error)
	SetMonto(context.Context, *Monto) (*Monto, error)
}

// UnimplementedPozoServiceServer can be embedded to have forward compatible implementations.
type UnimplementedPozoServiceServer struct {
}

func (*UnimplementedPozoServiceServer) GetMonto(ctx context.Context, req *Monto) (*Monto, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetMonto not implemented")
}
func (*UnimplementedPozoServiceServer) SetMonto(ctx context.Context, req *Monto) (*Monto, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SetMonto not implemented")
}

func RegisterPozoServiceServer(s *grpc.Server, srv PozoServiceServer) {
	s.RegisterService(&_PozoService_serviceDesc, srv)
}

func _PozoService_GetMonto_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Monto)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PozoServiceServer).GetMonto(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pozo.PozoService/GetMonto",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PozoServiceServer).GetMonto(ctx, req.(*Monto))
	}
	return interceptor(ctx, in, info, handler)
}

func _PozoService_SetMonto_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Monto)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PozoServiceServer).SetMonto(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pozo.PozoService/SetMonto",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PozoServiceServer).SetMonto(ctx, req.(*Monto))
	}
	return interceptor(ctx, in, info, handler)
}

var _PozoService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "pozo.PozoService",
	HandlerType: (*PozoServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetMonto",
			Handler:    _PozoService_GetMonto_Handler,
		},
		{
			MethodName: "SetMonto",
			Handler:    _PozoService_SetMonto_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "pozo.proto",
}
